### ISSUE TITLE
Closes background console when reloading

### ISSUE THREAD

**Issue by qimingweng** [arikw/chrome-extensions-reloader#10]
When reloading the extension, my background javascript console is closed. This is very difficult because I have to open it again from my `chrome://extensions`.

When reloading the extensions from `chrome://extensions`, the background console does not close.

**Comment by amitg87** [comment]
Reloading the extension is two step process - disable and enable.
Due to step 1 the background console is closed.

There is no way to invoke extension reload outside the extension. There is work-around extensions can trigger reload of themselves - recipe [here](https://github.com/arikw/chrome-extensions-reloader/issues/12)
